Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
// Seção de Declarações das variáveis 
a:  inteiro
b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 a <- 10
 b <-5
 escreva (a-b)
 escreva (a+b)
 escreva (a/b)
 escreva (a*b)
 
Fimalgoritmo
