Algoritmo "FATORIAL"
//Faça um algoritmo que gere o Fatorial de um número digitado pelo usuário

Var


 numero: inteiro
 contador: inteiro
 total: inteiro
 
Inicio

      
      escreval ("DIGITE UM NUMERO PARA QUE O FATORIAL SEJA CALCULADO")
       leia(numero)
       
      total<- 1
       
      para contador de 1 ate numero faca
       total<- contador * total
      fimpara
      
     escreval ("O TOTAL NUMERO E:")
     escreval (total)

Fimalgoritmo