Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
// Seção de Declarações das variáveis 
peso: real
altura:  real
imc: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
peso<-80
altura<-180
imc<- (peso)/(altura*altura)
escreva(imc)

Fimalgoritmo