Algoritmo "semnome"





Var

nI: inteiro




Inicio

escreval ("Escreva um numero inteiro")
leia (nI)

se (nI%2=0) e (nI>0) entao
escreval("O numero é par e positivo")

senao
se (nI%2=0) e (nI<0) entao
escreval("O numero é par e negativo")

senao
se (nI%2=1) e (nI>0) entao
escreval("O numero é impar")

senao
se (nI%2=1) e (nI<0) entao
escreval("O numero é impar")


fimse
fimse
fimse
fimse

Fimalgoritmo